name: Deploy Frontend to DigitalOcean

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/frontend:buildcache,mode=max

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/deployment
            docker-compose pull frontend
            docker-compose up -d frontend
            docker image prune -f

      # Verify Deployment by accessing the app in the browser
      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to stabilize..."
          sleep 10
          curl -sSf http://${{ secrets.DO_HOST }}
        continue-on-error: false  # Stops if this step fails
